# -*- coding: utf-8 -*-
"""Cat Adventure - Day 003/100 of Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQJRB8I69gOL7p7PaQEW0iaXpYPgybbQ
"""

print('''
😺😺😺😺😺😺😺😺😺😺😺😺😺😺😺
    Welcome to the Cat Adventure!
Begin your unforgetable journey here.
😺😺😺😺😺😺😺😺😺😺😺😺😺😺😺
''')

name = input('You are cursed to be a cat now. You should find another name.\nWhat is your name now? Type here: ')

walkthrough = input('''
Okay, {name}. Your journey has just begun!
Where do you want to go?
[a] Cafe
[b] Restaurant
[c] Small House
[d] Forest
''').lower()

if walkthrough == 'a':
  answer = input('You are going to the cafe right now. You find a pretty girl with the white skirt is calling you. Do you want to approach her?\nType Y or N: ').upper()
  if answer == 'Y':
    print('She is actually a criminal! She points a gun at you! Game over....')
  else:
    print(f'Luckily you didn\'t approach her. You see a gun behind her! She must be a criminal. Better run from here, {name}!')
elif walkthrough == 'b':
  answer = input('You are going to the restaurant right now. You find another three-colours cat is calling you. Do you want to approach her?\nType Y or N: ').upper()
  if answer == 'Y':
    print(f'Her name is Bety. She is very happy to have a friend like you, {name}! You will live at her big house from now. Congratulations!')
  else:
    print('That three-colours cat is disappointed because you do not approach her. Then, she calls her \'husband\' to kill you! Game over....')
elif walkthrough == 'c':
  answer = input('You are going to the small house right now. You find an old man who is sitting in his wheelchair. He is calling you. Do you want to approach him?\nType Y or N: ').upper()
  if answer == 'Y':
    print('His name is Benedict and he says that he is a veterinarian. He gives you a snack, but suddenly... your vision starts to fade. He actually gives you a sleeping pill! No one knows what will happen after that. Game over....')
  else:
    print(f'You do not approach him and suddenly you see the polices caught him. What happened? He is actually selling the drugs! You are safe now, {name}')
else:
  print('You are going to the forest and you see a witch is approaching you. \'Abracadabra!\', she shouts. And boom! You are being a human again!')