# -*- coding: utf-8 -*-
"""Password Generator (2nd version) - Day 005/100 of Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gLrjlyrosNggr71Sww-Dna-xgi3PEV1o
"""

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '+', '=', '<', '>', '?', '/', '[', '{', ']', '}']

import random

total_letter = int(input('How many letters would you like in your password: '))
total_number = int(input('How many numbers would you like in your password: '))
total_symbols = int(input('How many symbols would you like in your password: '))

letter = []
for i in range(total_letter):
  letter.append(random.choice(letters))

number = []
for i in range(total_number):
  number.append(random.choice(numbers))
5
symbol = []
for i in range(total_symbols):
  symbol.append(random.choice(symbols))

merged_list = letter + number + symbol
random.shuffle(merged_list)

password = ''
for i in merged_list:
  password += i

print(f'This is your unbreakable password: {password}')