# -*- coding: utf-8 -*-
"""Breast-Feed Time - Day 002/100 of Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FofmqmYT3YwzRnnTvnVdGaDb--aE1pty
"""

wake_up = int(input("What time do you wake up in the morning?\nType here (24h format): "))
feeding = wake_up + 1
print(f"Your 1st breast-feeding will be at {wake_up}.00 until {feeding}.00")
times = ""
for i in range(2,8):
  if i == 11:
    times = "st"
  elif i == 2 or i == 12:
    times = "nd"
  else:
    times = "th"
  feeding += 2
  print(f"Your {i}{times} breast-feeding will be at {round(feeding, 2):.2f} until {round(feeding + 1, 2):.2f}")
  feeding += 1

print("It is already midnight. Time to sleep, Amazing Mom!")